#std=c++11 is used because some functions works only in this compiler version
hw4: 	AdjList.h AdjList.cpp FlightMap.h FlightMap.cpp HashTable.h HashTable.cpp Stack.h Stack.cpp main.cpp
	g++ -std=c++11 *.cpp -o hw4