#std=c++11 is used because chrono functions works only in this compiler version
hw1: 	auxArrayFunctions.cpp auxArrayFunctions.h BinaryNode.cpp BinaryNode.h 	BinarySearchTree.h BinarySearchTree.cpp main.cpp
	g++ -std=c++11 *.cpp -o hw2